<?php
return [
    [
        "text"         => "Introduction",
        "title"        => "Introduction",
        'nepali_title' => "परिचय",
        "class"        => "nav-item",
        "order"        => 1,
        "icon"         => "<i class='fa fa-comment'></i>",
        "is_active"    => true,
        "route"        => "introduction",
        "children"     => [
            [
                "text"         => "Edit Introduction",
                "title"        => "Edit Introduction",
                'nepali_title' => "परिचय",
                "class"        => "nav-item",
                "order"        => 1,
                "icon"         => "<i class='fa fa-edit'></i>",
                "is_active"    => true,
                "route"        => "introduction.edit",
            ],
        ],
    ],
    [
        "text"         => "citizen charter",
        "title"        => "Citizen Charter",
        'nepali_title' => "समाचार",
        "class"        => "nav-item",
        "order"        => 4,
        "icon"         => "<i class='fa fa-file-text-o'></i>",
        "is_active"    => true,
        "route"        => "citizen-charter",
        "children"     => [
            [
                "text"         => "all citizen charter",
                "title"        => "All Citizen Charter",
                'nepali_title' => "समाचार",
                "class"        => "nav-item",
                "order"        => 1,
                "icon"         => "<i class='fa fa-file-text-o'></i>",
                "is_active"    => true,
                "route"        => "citizen-charter.index",
            ],
            [
                "text"         => "add citizen charter",
                "title"        => "Add citizen charter",
                'nepali_title' => "समाचार थप गर्नुहोस्",
                "class"        => "nav-item",
                "order"        => 2,
                "icon"         => "<i class='fa fa-plus'></i>",
                "is_active"    => true,
                "route"        => "citizen-charter.create",
            ],
        ],
    ],
    [
        "text"         => "Staff Details",
        "title"        => "Staff Details",
        'nepali_title' => "कर्मचारी",
        "class"        => "nav-item",
        "order"        => 3,
        "icon"         => "<i class='fa fa-group'></i>",
        "is_active"    => true,
        "route"        => "staff",
        "children"     => [
            [
                "text"         => "Staffs",
                "title"        => "Staffs",
                'nepali_title' => "कर्मचारीहरू",
                "class"        => "nav-item",
                "order"        => 1,
                "icon"         => "<i class='fa fa-group'></i>",
                "is_active"    => true,
                "route"        => "staff.index",
            ],
            [
                "text"         => "Add New",
                "title"        => "Add New",
                'nepali_title' => "नयाँ कर्मचारी थप्नुहोस्",
                "class"        => "nav-item",
                "order"        => 2,
                "icon"         => "<i class='fa fa-plus'></i>",
                "is_active"    => true,
                "route"        => "staff.create",
            ],
        ],
    ],
    [
        "text"         => "notice/news",
        "title"        => "Notice/News",
        'nepali_title' => "समाचार",
        "class"        => "nav-item",
        "order"        => 4,
        "icon"         => "<i class='fa fa-newspaper-o'></i>",
        "is_active"    => true,
        "route"        => "news",
        "children"     => [
            [
                "text"         => "all news",
                "title"        => "All News",
                'nepali_title' => "समाचार",
                "class"        => "nav-item",
                "order"        => 1,
                "icon"         => "<i class='fa fa-newspaper-o'></i>",
                "is_active"    => true,
                "route"        => "news.index",
            ],
            [
                "text"         => "add news",
                "title"        => "Add News",
                'nepali_title' => "समाचार थप गर्नुहोस्",
                "class"        => "nav-item",
                "order"        => 2,
                "icon"         => "<i class='fa fa-plus'></i>",
                "is_active"    => true,
                "route"        => "news.create",
            ],
        ],
    ],
    [
        "text"         => "download",
        "title"        => "download",
        'nepali_title' => "समाचार",
        "class"        => "nav-item",
        "order"        => 4,
        "icon"         => "<i class='fa fa-cloud-download'></i>",
        "is_active"    => true,
        "route"        => "download",
        "children"     => [
            [
                "text"         => "all download",
                "title"        => "All Download",
                'nepali_title' => "समाचार",
                "class"        => "nav-item",
                "order"        => 1,
                "icon"         => "<i class='fa fa-cloud-download'></i>",
                "is_active"    => true,
                "route"        => "download.index",
            ],
            [
                "text"         => "add download",
                "title"        => "Add Download",
                'nepali_title' => "समाचार थप गर्नुहोस्",
                "class"        => "nav-item",
                "order"        => 2,
                "icon"         => "<i class='fa fa-plus'></i>",
                "is_active"    => true,
                "route"        => "download.create",
            ],
        ],
    ],
    [
        "text"         => "public procurement",
        "title"        => "Public Procurement",
        'nepali_title' => "समाचार",
        "class"        => "nav-item",
        "order"        => 4,
        "icon"         => "<i class='fa fa-hand-grab-o'></i>",
        "is_active"    => true,
        "route"        => "public-procurement",
        "children"     => [
            [
                "text"         => "all public procurement",
                "title"        => "All Public Procurement",
                'nepali_title' => "समाचार",
                "class"        => "nav-item",
                "order"        => 1,
                "icon"         => "<i class='fa fa-hand-grab-o'></i>",
                "is_active"    => true,
                "route"        => "public-procurement.index",
            ],
            [
                "text"         => "add public procurement",
                "title"        => "Add Public Procurement",
                'nepali_title' => "समाचार थप गर्नुहोस्",
                "class"        => "nav-item",
                "order"        => 2,
                "icon"         => "<i class='fa fa-plus'></i>",
                "is_active"    => true,
                "route"        => "public-procurement.create",
            ],
        ],
    ],
    [
        "text"         => "Gallery",
        "title"        => "Gallery",
        'nepali_title' => "ग्यालरी",
        "class"        => "nav-item",
        "order"        => 3,
        "icon"         => "<i class='fa fa-image'></i>",
        "is_active"    => true,
        "route"        => "gallery",
        "children"     => [
            [
                "text"         => "Categories",
                "title"        => "Categories",
                'nepali_title' => "कोटीहरू",
                "class"        => "nav-item",
                "order"        => 1,
                "icon"         => "<i class='fa fa-image'></i>",
                "is_active"    => true,
                "route"        => "gallery.categories",
            ],
            [
                "text"         => "Images",
                "title"        => "Images",
                'nepali_title' => "फोटोहरू",
                "class"        => "nav-item",
                "order"        => 2,
                "icon"         => "<i class='fa fa-image'></i>",
                "is_active"    => true,
                "route"        => "gallery.images",
            ],
            [
                "text"         => "Videos",
                "title"        => "Videos",
                'nepali_title' => "भिडियोहरू",
                "class"        => "nav-item",
                "order"        => 3,
                "icon"         => "<i class='fa fa-video-camera'></i>",
                "is_active"    => true,
                "route"        => "gallery.videos",
            ],
        ],
    ],
    [
        "text"         => "planning and project",
        "title"        => "Planning and Project",
        'nepali_title' => "समाचार",
        "class"        => "nav-item",
        "order"        => 4,
        "icon"         => "<i class='fa fa-clock-o'></i>",
        "is_active"    => true,
        "route"        => "planning-project",
        "children"     => [
            [
                "text"         => "all planning  and project",
                "title"        => "All Planning and Project",
                'nepali_title' => "समाचार",
                "class"        => "nav-item",
                "order"        => 1,
                "icon"         => "<i class='fa fa-clock-o'></i>",
                "is_active"    => true,
                "route"        => "planning-project.index",
            ],
            [
                "text"         => "add planning and project",
                "title"        => "Add Planning and project",
                'nepali_title' => "समाचार थप गर्नुहोस्",
                "class"        => "nav-item",
                "order"        => 2,
                "icon"         => "<i class='fa fa-plus'></i>",
                "is_active"    => true,
                "route"        => "planning-project.create",
            ],
        ],
    ],
    [
        "text"         => "budget and program",
        "title"        => "Budget and Program",
        'nepali_title' => "समाचार",
        "class"        => "nav-item",
        "order"        => 4,
        "icon"         => "<i class='fa fa-money'></i>",
        "is_active"    => true,
        "route"        => "budget-program",
        "children"     => [
            [
                "text"         => "all budget and program",
                "title"        => "All Budget and Program",
                'nepali_title' => "समाचार",
                "class"        => "nav-item",
                "order"        => 1,
                "icon"         => "<i class='fa fa-money'></i>",
                "is_active"    => true,
                "route"        => "budget-program.index",
            ],
            [
                "text"         => "add budget and program",
                "title"        => "Add Budget and Program",
                'nepali_title' => "समाचार थप गर्नुहोस्",
                "class"        => "nav-item",
                "order"        => 2,
                "icon"         => "<i class='fa fa-plus'></i>",
                "is_active"    => true,
                "route"        => "budget-program.create",
            ],
        ],
    ],
    [
        "text"         => "important contacts",
        "title"        => "Important Contacts",
        'nepali_title' => "महत्त्वपूर्ण सम्पर्कहरू",
        "class"        => "nav-item",
        "order"        => 4,
        "icon"         => "<i class='fa fa-credit-card'></i>",
        "is_active"    => true,
        "route"        => "important-contact",
        "children"     => [
            [
                "text"         => "contact categories",
                "title"        => "Contact Categories",
                'nepali_title' => "कोटीहरू",
                "class"        => "nav-item",
                "order"        => 1,
                "icon"         => "<i class='fa fa-credit-card'></i>",
                "is_active"    => true,
                "route"        => "important-contact.categories",
            ],
        ],
    ],
    [
        "text"         => "tax and fee",
        "title"        => "Tax and Fee",
        'nepali_title' => "समाचार",
        "class"        => "nav-item",
        "order"        => 4,
        "icon"         => "<i class='fa fa-briefcase'></i>",
        "is_active"    => true,
        "route"        => "tax-fee",
        "children"     => [
            [
                "text"         => "all tax and fee",
                "title"        => "All Tax and Fee",
                'nepali_title' => "समाचार",
                "class"        => "nav-item",
                "order"        => 1,
                "icon"         => "<i class='fa fa-briefcase'></i>",
                "is_active"    => true,
                "route"        => "tax-fee.index",
            ],
            [
                "text"         => "add tax and fee",
                "title"        => "Add tax and fee",
                'nepali_title' => "समाचार थप गर्नुहोस्",
                "class"        => "nav-item",
                "order"        => 2,
                "icon"         => "<i class='fa fa-plus'></i>",
                "is_active"    => true,
                "route"        => "tax-fee.create",
            ],
        ],
    ],
    [
        "text"         => "law and regulations",
        "title"        => "Law and Regulations",
        'nepali_title' => "समाचार",
        "class"        => "nav-item",
        "order"        => 4,
        "icon"         => "<i class='fa fa-balance-scale'></i>",
        "is_active"    => true,
        "route"        => "law-regulation",
        "children"     => [
            [
                "text"         => "all law and regulation",
                "title"        => "All Law and Regulation",
                'nepali_title' => "समाचार",
                "class"        => "nav-item",
                "order"        => 1,
                "icon"         => "<i class='fa fa-balance-scale'></i>",
                "is_active"    => true,
                "route"        => "law-regulation.index",
            ],
            [
                "text"         => "add law and regulation",
                "title"        => "Add Law and Regulation",
                'nepali_title' => "समाचार थप गर्नुहोस्",
                "class"        => "nav-item",
                "order"        => 2,
                "icon"         => "<i class='fa fa-plus'></i>",
                "is_active"    => true,
                "route"        => "law-regulation.create",
            ],
        ],
    ],
    [
        "text"         => "ward profile",
        "title"        => "Ward Profile",
        'nepali_title' => "वार्ड प्रोफाइल",
        "class"        => "nav-item",
        "order"        => 4,
        "icon"         => "<i class='fa fa-book'></i>",
        "is_active"    => true,
        "route"        => "ward-profile",
        "children"     => [
            [
                "text"         => "all ward profile",
                "title"        => "All Ward Profile",
                'nepali_title' => "वार्ड प्रोफाइल",
                "class"        => "nav-item",
                "order"        => 1,
                "icon"         => "<i class='fa fa-book'></i>",
                "is_active"    => true,
                "route"        => "ward-profile.index",
            ],
            [
                "text"         => "add ward profile",
                "title"        => "Add Ward Profile",
                'nepali_title' => "वार्ड प्रोफाइल थप गर्नुहोस्",
                "class"        => "nav-item",
                "order"        => 2,
                "icon"         => "<i class='fa fa-plus'></i>",
                "is_active"    => true,
                "route"        => "ward-profile.create",
            ],
        ],
    ],

    [
        "text"         => "contact us info",
        "title"        => "Contact Us Info",
        'nepali_title' => "सम्पर्क जानकारी",
        "class"        => "nav-item",
        "order"        => 4,
        "icon"         => "<i class='fa fa-info'></i>",
        "is_active"    => true,
        "route"        => "contact-us-info",
        "children"     => [
            [
                "text"         => "edit contact us info",
                "title"        => "Edit Contact Us Info",
                'nepali_title' => "सम्पर्क जानकारी सम्पादन गर्नुहोस्",
                "class"        => "nav-item",
                "order"        => 1,
                "icon"         => "<i class='fa fa-edit'></i>",
                "is_active"    => true,
                "route"        => "contact-us-info.edit",
            ],
        ],
    ],
];
